name: Sync Resources

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Run sync
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/the-balance-ffxiv/discord-static-resource-bot:master
          options: -v ${{ github.workspace }}/data:/app/data -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}

